### ISSUE TITLE
Move specialized collision code outside of state.game

### ISSUE THREAD

**Issue by jpfed** [jpfed/Adrift#24]
GameObject can define tryCollide etc. Individual classes should provide collision handlers to state.game (not during object instantiation; it can happen outside each class's table, so that when the object's source file gets required, the collision handler is registered once.)

**Comment by dgfitch** [comment]
Problem here is that the order actually matters, and a lot of the interactions require that things are already loaded. I've moved it out of `state.game` and into `objects`, but if you have better ideas for how to clean it up further, keep going...
